import type { PublicJobListItem } from "./jobsListTypes";

export const publicJobs: PublicJobListItem[] = [
  { id: "1", logo: "VN", title: "Frontend Developer Intern", companyName: "VietNext Software", salary: "8 - 12 triệu", salaryMax: 12, location: "Hà Nội", industry: "Công nghệ thông tin", experienceYears: 0, experienceLabel: "Thực tập", level: "Intern", jobType: "Toàn thời gian", workMode: "Hybrid", skills: ["React", "TypeScript", "Tailwind"], postedAt: "2026-07-10", deadline: "2026-07-30", applicants: 42, status: "featured", matchScore: 94 },
  { id: "2", logo: "TC", title: "Java Backend Fresher", companyName: "TechCore Solutions", salary: "10 - 15 triệu", salaryMax: 15, location: "TP. Hồ Chí Minh", industry: "Công nghệ thông tin", experienceYears: 1, experienceLabel: "0-1 năm", level: "Fresher", jobType: "Toàn thời gian", workMode: "Onsite", skills: ["Java", "Spring Boot", "PostgreSQL"], postedAt: "2026-07-09", deadline: "2026-08-05", applicants: 58, status: "featured", matchScore: 91 },
  { id: "3", logo: "DA", title: "Data Analyst Intern", companyName: "DataAide Analytics", salary: "7 - 10 triệu", salaryMax: 10, location: "Đà Nẵng", industry: "Phân tích dữ liệu", experienceYears: 0, experienceLabel: "Thực tập", level: "Intern", jobType: "Thực tập", workMode: "Remote", skills: ["SQL", "Power BI", "Python"], postedAt: "2026-07-08", deadline: "2026-08-12", applicants: 31, status: "published", matchScore: 88 },
  { id: "4", logo: "FI", title: "Business Analyst Junior", companyName: "FinInsight", salary: "12 - 18 triệu", salaryMax: 18, location: "Hà Nội", industry: "Kinh doanh", experienceYears: 2, experienceLabel: "1-2 năm", level: "Junior", jobType: "Toàn thời gian", workMode: "Hybrid", skills: ["UML", "Agile", "SQL"], postedAt: "2026-07-07", deadline: "2026-08-18", applicants: 27, status: "urgent", matchScore: 86 },
  { id: "5", logo: "PX", title: "UI/UX Designer Fresher", companyName: "PixelCraft Studio", salary: "9 - 13 triệu", salaryMax: 13, location: "TP. Hồ Chí Minh", industry: "Thiết kế", experienceYears: 1, experienceLabel: "0-1 năm", level: "Fresher", jobType: "Toàn thời gian", workMode: "Onsite", skills: ["Figma", "Prototype", "Design System"], postedAt: "2026-07-06", deadline: "2026-08-22", applicants: 34, status: "published", matchScore: 83 },
  { id: "6", logo: "CL", title: "DevOps Intern", companyName: "CloudLeap", salary: "8 - 11 triệu", salaryMax: 11, location: "Remote", industry: "Công nghệ thông tin", experienceYears: 0, experienceLabel: "Thực tập", level: "Intern", jobType: "Thực tập", workMode: "Remote", skills: ["Docker", "Linux", "CI/CD"], postedAt: "2026-07-05", deadline: "2026-08-28", applicants: 22, status: "featured", matchScore: 90 },
  { id: "7", logo: "MK", title: "Digital Marketing Executive", companyName: "MarketHub", salary: "11 - 16 triệu", salaryMax: 16, location: "Hà Nội", industry: "Marketing", experienceYears: 2, experienceLabel: "1-2 năm", level: "Junior", jobType: "Toàn thời gian", workMode: "Hybrid", skills: ["SEO", "Content", "Analytics"], postedAt: "2026-07-04", deadline: "2026-07-26", applicants: 63, status: "urgent", matchScore: 78 },
  { id: "8", logo: "AC", title: "Kế toán tổng hợp Junior", companyName: "AnCom Finance", salary: "10 - 14 triệu", salaryMax: 14, location: "TP. Hồ Chí Minh", industry: "Kế toán", experienceYears: 2, experienceLabel: "1-2 năm", level: "Junior", jobType: "Toàn thời gian", workMode: "Onsite", skills: ["Excel", "Thuế", "Báo cáo"], postedAt: "2026-07-03", deadline: "2026-08-01", applicants: 19, status: "published", matchScore: 72 },
  { id: "9", logo: "HR", title: "HR Recruitment Specialist", companyName: "TalentBridge", salary: "13 - 20 triệu", salaryMax: 20, location: "Hà Nội", industry: "Nhân sự", experienceYears: 3, experienceLabel: "3+ năm", level: "Middle", jobType: "Toàn thời gian", workMode: "Hybrid", skills: ["Tuyển dụng", "Phỏng vấn", "ATS"], postedAt: "2026-07-02", deadline: "2026-08-09", applicants: 25, status: "featured", matchScore: 81 },
  { id: "10", logo: "BN", title: "Financial Analyst", companyName: "BlueNest Capital", salary: "18 - 28 triệu", salaryMax: 28, location: "TP. Hồ Chí Minh", industry: "Tài chính", experienceYears: 3, experienceLabel: "3+ năm", level: "Middle", jobType: "Toàn thời gian", workMode: "Onsite", skills: ["Excel", "Forecast", "Power BI"], postedAt: "2026-07-01", deadline: "2026-08-15", applicants: 37, status: "published", matchScore: 84 },
  { id: "11", logo: "EC", title: "E-commerce Operations Executive", companyName: "EcoCart", salary: "12 - 17 triệu", salaryMax: 17, location: "Đà Nẵng", industry: "Kinh doanh", experienceYears: 2, experienceLabel: "1-2 năm", level: "Junior", jobType: "Toàn thời gian", workMode: "Onsite", skills: ["Marketplace", "Excel", "Vận hành"], postedAt: "2026-06-30", deadline: "2026-07-29", applicants: 44, status: "published", matchScore: 76 },
  { id: "12", logo: "AI", title: "Machine Learning Intern", companyName: "AIWorks Lab", salary: "9 - 14 triệu", salaryMax: 14, location: "Hà Nội", industry: "Phân tích dữ liệu", experienceYears: 0, experienceLabel: "Thực tập", level: "Intern", jobType: "Thực tập", workMode: "Hybrid", skills: ["Python", "TensorFlow", "NLP"], postedAt: "2026-06-29", deadline: "2026-08-04", applicants: 51, status: "featured", matchScore: 92 },
  { id: "13", logo: "QA", title: "Manual QA Tester Fresher", companyName: "QualityApps", salary: "8 - 12 triệu", salaryMax: 12, location: "TP. Hồ Chí Minh", industry: "Công nghệ thông tin", experienceYears: 1, experienceLabel: "0-1 năm", level: "Fresher", jobType: "Toàn thời gian", workMode: "Onsite", skills: ["Test case", "Jira", "API"], postedAt: "2026-06-28", deadline: "2026-07-25", applicants: 46, status: "urgent", matchScore: 80 },
  { id: "14", logo: "MO", title: "Mobile Developer Flutter", companyName: "MobiOne", salary: "18 - 30 triệu", salaryMax: 30, location: "Remote", industry: "Công nghệ thông tin", experienceYears: 3, experienceLabel: "3+ năm", level: "Middle", jobType: "Toàn thời gian", workMode: "Remote", skills: ["Flutter", "Dart", "Firebase"], postedAt: "2026-06-27", deadline: "2026-08-20", applicants: 29, status: "featured", matchScore: 87 },
  { id: "15", logo: "CS", title: "Customer Success Associate", companyName: "CareSoft", salary: "10 - 15 triệu", salaryMax: 15, location: "Hà Nội", industry: "Kinh doanh", experienceYears: 1, experienceLabel: "0-1 năm", level: "Fresher", jobType: "Toàn thời gian", workMode: "Hybrid", skills: ["CRM", "Giao tiếp", "Báo cáo"], postedAt: "2026-06-26", deadline: "2026-07-31", applicants: 33, status: "published", matchScore: 74 },
  { id: "16", logo: "BD", title: "Brand Designer", companyName: "BoldStudio", salary: "14 - 22 triệu", salaryMax: 22, location: "Đà Nẵng", industry: "Thiết kế", experienceYears: 3, experienceLabel: "3+ năm", level: "Middle", jobType: "Toàn thời gian", workMode: "Hybrid", skills: ["Branding", "Illustrator", "Figma"], postedAt: "2026-06-25", deadline: "2026-08-06", applicants: 17, status: "published", matchScore: 79 },
  { id: "17", logo: "AD", title: "Performance Marketing Intern", companyName: "AdNova", salary: "6 - 9 triệu", salaryMax: 9, location: "Remote", industry: "Marketing", experienceYears: 0, experienceLabel: "Thực tập", level: "Intern", jobType: "Bán thời gian", workMode: "Remote", skills: ["Ads", "Landing Page", "A/B Test"], postedAt: "2026-06-24", deadline: "2026-07-27", applicants: 39, status: "published", matchScore: 75 },
  { id: "18", logo: "ST", title: "Senior React Engineer", companyName: "StarTech", salary: "35 - 55 triệu", salaryMax: 55, location: "TP. Hồ Chí Minh", industry: "Công nghệ thông tin", experienceYears: 5, experienceLabel: "5+ năm", level: "Senior", jobType: "Toàn thời gian", workMode: "Hybrid", skills: ["React", "Next.js", "Node.js"], postedAt: "2026-06-23", deadline: "2026-08-25", applicants: 21, status: "featured", matchScore: 89 },
  { id: "19", logo: "TX", title: "Tax Accountant", companyName: "TaxPro Vietnam", salary: "16 - 24 triệu", salaryMax: 24, location: "Hà Nội", industry: "Kế toán", experienceYears: 3, experienceLabel: "3+ năm", level: "Middle", jobType: "Toàn thời gian", workMode: "Onsite", skills: ["Thuế", "MISA", "Báo cáo tài chính"], postedAt: "2026-06-22", deadline: "2026-08-11", applicants: 16, status: "published", matchScore: 70 },
  { id: "20", logo: "PG", title: "Product Manager Junior", companyName: "ProductGo", salary: "20 - 32 triệu", salaryMax: 32, location: "Remote", industry: "Công nghệ thông tin", experienceYears: 3, experienceLabel: "3+ năm", level: "Middle", jobType: "Toàn thời gian", workMode: "Remote", skills: ["Roadmap", "User Research", "Agile"], postedAt: "2026-06-21", deadline: "2026-08-17", applicants: 28, status: "urgent", matchScore: 85 },
];
