import type { PublicCompanyListItem } from "./companiesListTypes";

export const publicCompanies: PublicCompanyListItem[] = [
  {
    id: "1",
    cover: "bg-gradient-to-r from-slate-900 to-brand-700",
    logo: "VN",
    name: "VietNext Software",
    verified: true,
    industry: "Công nghệ thông tin",
    size: "100-300 nhân sự",
    location: "Hà Nội",
    description: "Phát triển sản phẩm web, nền tảng quản trị và giải pháp chuyển đổi số cho doanh nghiệp Việt Nam.",
    openJobs: 18,
  },
  {
    id: "2",
    cover: "bg-gradient-to-r from-emerald-800 to-slate-900",
    logo: "TC",
    name: "TechCore Solutions",
    verified: true,
    industry: "Phần mềm doanh nghiệp",
    size: "300-500 nhân sự",
    location: "TP. Hồ Chí Minh",
    description: "Cung cấp giải pháp backend, ERP, tích hợp dữ liệu và vận hành hệ thống quy mô lớn.",
    openJobs: 24,
  },
  {
    id: "3",
    cover: "bg-gradient-to-r from-blue-900 to-cyan-700",
    logo: "DA",
    name: "DataAide Analytics",
    verified: true,
    industry: "Phân tích dữ liệu",
    size: "50-100 nhân sự",
    location: "Đà Nẵng",
    description: "Tư vấn phân tích dữ liệu, xây dựng dashboard và tự động hóa báo cáo cho đội ngũ vận hành.",
    openJobs: 9,
  },
  {
    id: "4",
    cover: "bg-gradient-to-r from-slate-800 to-amber-700",
    logo: "FI",
    name: "FinInsight",
    verified: true,
    industry: "Tài chính công nghệ",
    size: "100-300 nhân sự",
    location: "Hà Nội",
    description: "Nền tảng phân tích tài chính và quản lý dòng tiền dành cho doanh nghiệp vừa và nhỏ.",
    openJobs: 12,
  },
  {
    id: "5",
    cover: "bg-gradient-to-r from-zinc-900 to-rose-700",
    logo: "PX",
    name: "PixelCraft Studio",
    verified: false,
    industry: "Thiết kế sản phẩm",
    size: "30-80 nhân sự",
    location: "TP. Hồ Chí Minh",
    description: "Studio thiết kế giao diện, nhận diện thương hiệu và nguyên mẫu sản phẩm số cho startup.",
    openJobs: 7,
  },
  {
    id: "6",
    cover: "bg-gradient-to-r from-indigo-900 to-sky-700",
    logo: "CL",
    name: "CloudLeap",
    verified: true,
    industry: "Cloud & DevOps",
    size: "80-150 nhân sự",
    location: "Remote",
    description: "Dịch vụ cloud, DevOps, CI/CD và tối ưu hạ tầng cho các đội sản phẩm tăng trưởng nhanh.",
    openJobs: 11,
  },
  {
    id: "7",
    cover: "bg-gradient-to-r from-slate-900 to-orange-700",
    logo: "MK",
    name: "MarketHub",
    verified: false,
    industry: "Marketing",
    size: "50-100 nhân sự",
    location: "Hà Nội",
    description: "Agency triển khai chiến dịch digital marketing, SEO, content và performance cho thương hiệu trẻ.",
    openJobs: 6,
  },
  {
    id: "8",
    cover: "bg-gradient-to-r from-stone-900 to-lime-700",
    logo: "AC",
    name: "AnCom Finance",
    verified: true,
    industry: "Kế toán",
    size: "30-80 nhân sự",
    location: "TP. Hồ Chí Minh",
    description: "Dịch vụ kế toán, thuế và báo cáo tài chính cho doanh nghiệp thương mại và sản xuất.",
    openJobs: 5,
  },
  {
    id: "9",
    cover: "bg-gradient-to-r from-slate-900 to-teal-700",
    logo: "TB",
    name: "TalentBridge",
    verified: true,
    industry: "Nhân sự",
    size: "80-150 nhân sự",
    location: "Hà Nội",
    description: "Nền tảng hỗ trợ tuyển dụng, đánh giá ứng viên và quản lý pipeline cho doanh nghiệp.",
    openJobs: 14,
  },
  {
    id: "10",
    cover: "bg-gradient-to-r from-neutral-900 to-blue-700",
    logo: "BN",
    name: "BlueNest Capital",
    verified: false,
    industry: "Tài chính",
    size: "100-300 nhân sự",
    location: "TP. Hồ Chí Minh",
    description: "Công ty tư vấn đầu tư, phân tích thị trường và xây dựng báo cáo tài chính chuyên sâu.",
    openJobs: 8,
  },
  {
    id: "11",
    cover: "bg-gradient-to-r from-slate-900 to-green-700",
    logo: "EC",
    name: "EcoCart",
    verified: true,
    industry: "Thương mại điện tử",
    size: "300-500 nhân sự",
    location: "Đà Nẵng",
    description: "Nền tảng thương mại điện tử tập trung vào vận hành bền vững, logistics và trải nghiệm khách hàng.",
    openJobs: 16,
  },
  {
    id: "12",
    cover: "bg-gradient-to-r from-violet-900 to-slate-800",
    logo: "AW",
    name: "AIWorks Lab",
    verified: true,
    industry: "Trí tuệ nhân tạo",
    size: "50-100 nhân sự",
    location: "Remote",
    description: "Phòng nghiên cứu ứng dụng AI trong xử lý ngôn ngữ, phân tích dữ liệu và tự động hóa quy trình.",
    openJobs: 10,
  },
];
