"""Stable identifiers for the additive Student Recommendation V3 contract."""

from v2.constants import (
    ALGORITHM,
    ENGLISH_LANGUAGE_CONFIDENCE_THRESHOLD,
    PROCESSING_VERSION,
    PUBLIC_SCORE_QUANTUM,
    PUBLIC_SCORE_ROUNDING,
)


ALGORITHM_VERSION = "bilingual-recommendation-v3"
LANGUAGE_CONFIDENCE_THRESHOLD = ENGLISH_LANGUAGE_CONFIDENCE_THRESHOLD


__all__ = [
    "ALGORITHM",
    "ALGORITHM_VERSION",
    "LANGUAGE_CONFIDENCE_THRESHOLD",
    "PROCESSING_VERSION",
    "PUBLIC_SCORE_QUANTUM",
    "PUBLIC_SCORE_ROUNDING",
]
