import type { CandidateCvItem } from "./candidateCvTypes";

export const defaultCandidateCvs: CandidateCvItem[] = [
  {
    id: "cv-frontend",
    fileName: "Nguyen-Minh-Anh-Frontend-CV.pdf",
    fileType: "PDF",
    size: "1.8 MB",
    uploadedAt: "2026-07-01",
    updatedAt: "2026-07-08",
    status: "success",
    score: 82,
    isDefault: true,
    isPublic: true,
    recruiterViews: 12,
    extractedSkills: ["React", "TypeScript", "Tailwind CSS", "Git"],
    missingFields: ["Chứng chỉ"],
    warnings: ["Nên bổ sung số liệu kết quả trong phần kinh nghiệm."],
    analysisConfirmed: false,
  },
  {
    id: "cv-general",
    fileName: "Nguyen-Minh-Anh-General-CV.pdf",
    fileType: "PDF",
    size: "1.5 MB",
    uploadedAt: "2026-06-20",
    updatedAt: "2026-06-22",
    status: "analyzing",
    score: 48,
    isDefault: false,
    isPublic: false,
    recruiterViews: 4,
    extractedSkills: ["HTML", "CSS", "JavaScript"],
    missingFields: ["Dự án", "Mục tiêu nghề nghiệp"],
    warnings: ["Hệ thống đang phân tích lại nội dung CV."],
    analysisConfirmed: false,
  },
  {
    id: "cv-english",
    fileName: "Nguyen-Minh-Anh-English-CV.docx",
    fileType: "DOCX",
    size: "980 KB",
    uploadedAt: "2026-06-10",
    updatedAt: "2026-06-10",
    status: "failed",
    score: 0,
    isDefault: false,
    isPublic: false,
    recruiterViews: 1,
    extractedSkills: [],
    missingFields: ["Không đọc được nội dung"],
    warnings: ["Tệp DOCX bị lỗi định dạng, vui lòng tải lại hoặc chuyển sang PDF."],
    analysisConfirmed: false,
  },
];
