export const breadcrumbLabels: Record<string, string> = {
  candidate: "Ứng viên",
  recruiter: "Nhà tuyển dụng",
  admin: "Quản trị viên",
  dashboard: "Tổng quan",
  jobs: "Việc làm",
  companies: "Công ty",
  "career-resources": "Cẩm nang nghề nghiệp",
  profile: "Hồ sơ cá nhân",
  cvs: "Quản lý CV",
  applications: "Ứng tuyển",
  interviews: "Phỏng vấn",
  invitations: "Lời mời ứng tuyển",
  messages: "Tin nhắn",
  notifications: "Thông báo",
  settings: "Cài đặt",
  company: "Hồ sơ công ty",
  campaigns: "Chiến dịch",
  candidates: "Ứng viên",
  pipeline: "Pipeline tuyển dụng",
  members: "Thành viên",
  reports: "Báo cáo",
  users: "Người dùng",
  categories: "Danh mục",
  analytics: "Thống kê",
  "audit-logs": "Nhật ký hệ thống",
  "system-settings": "Cấu hình",
  saved: "Đã lưu",
  "saved-searches": "Tìm kiếm đã lưu",
  "saved-candidates": "Hồ sơ đã lưu",
  recommended: "Gợi ý",
  "recommended-candidates": "Ứng viên được gợi ý",
  upload: "Tải CV",
  analysis: "Phân tích",
  edit: "Chỉnh sửa",
  "edit-extracted-data": "Chỉnh sửa dữ liệu trích xuất",
  review: "Đánh giá",
  create: "Tạo mới",
  pending: "Chờ duyệt",
  verification: "Xác thực",
  preferences: "Mong muốn nghề nghiệp",
  account: "Tài khoản",
  security: "Bảo mật",
  privacy: "Quyền riêng tư",
  "candidate-search": "Tìm kiếm ứng viên",
  statistics: "Thống kê",
  "recruitment-process": "Quy trình tuyển dụng",
  "email-templates": "Mẫu email",
  industries: "Ngành nghề",
  "job-titles": "Chức danh",
  skills: "Kỹ năng",
  locations: "Địa điểm",
  "job-types": "Loại việc làm",
  "experience-levels": "Cấp bậc kinh nghiệm",
  errors: "Lỗi phân tích",
  "recommendation-system": "Hệ thống gợi ý",
  configuration: "Cấu hình",
  content: "Nội dung",
  articles: "Bài viết",
  banners: "Banner",
  pages: "Trang nội dung",
};
