import type { AppRoute } from "../types/navigation";

export const publicRoutes: AppRoute[] = [
  { path: "/", title: "Trang chủ", description: "Cổng thông tin việc làm và gợi ý nghề nghiệp cho sinh viên IT.", nextPath: "/jobs", nextLabel: "Tìm việc làm" },
  { path: "/jobs", title: "Danh sách việc làm", description: "Tìm kiếm và lọc các công việc phù hợp.", nextPath: "/jobs/1", nextLabel: "Xem chi tiết việc làm" },
  { path: "/jobs/:jobId", title: "Chi tiết việc làm", description: "Thông tin vị trí, công ty, yêu cầu và dữ liệu tuyển dụng hiện có.", nextPath: "/login", nextLabel: "Đăng nhập để ứng tuyển" },
  { path: "/companies", title: "Danh sách công ty", description: "Khám phá các doanh nghiệp đang tuyển dụng.", nextPath: "/companies/1", nextLabel: "Xem công ty" },
  { path: "/companies/:companyId", title: "Chi tiết công ty", description: "Hồ sơ công ty và danh sách việc làm đang tuyển." },
  { path: "/career-resources", title: "Cẩm nang nghề nghiệp", description: "Bài viết và tài nguyên định hướng nghề nghiệp.", nextPath: "/career-resources/cv-tips", nextLabel: "Đọc bài viết" },
  { path: "/career-resources/:slug", title: "Chi tiết cẩm nang", description: "Nội dung bài viết nghề nghiệp." },
  { path: "/about", title: "Giới thiệu", description: "Thông tin tổng quan về hệ thống gợi ý việc làm." },
  { path: "/contact", title: "Liên hệ", description: "Thông tin liên hệ và kênh hỗ trợ." },
  { path: "/privacy-policy", title: "Chính sách bảo mật", description: "Chính sách bảo mật dữ liệu người dùng." },
  { path: "/terms", title: "Điều khoản sử dụng", description: "Điều khoản sử dụng nền tảng." },
];

export const authRoutes: AppRoute[] = [
  { path: "/login", title: "Đăng nhập", description: "Đăng nhập để truy cập đúng vai trò tài khoản." },
  { path: "/register", title: "Đăng ký", description: "Chọn loại tài khoản ứng viên hoặc nhà tuyển dụng.", nextPath: "/register/candidate", nextLabel: "Đăng ký ứng viên" },
  { path: "/register/candidate", title: "Đăng ký ứng viên", description: "Form đăng ký tài khoản ứng viên.", nextPath: "/login", nextLabel: "Đến đăng nhập" },
  { path: "/register/recruiter", title: "Đăng ký nhà tuyển dụng", description: "Form đăng ký tài khoản nhà tuyển dụng.", nextPath: "/login", nextLabel: "Đến đăng nhập" },
  { path: "/forgot-password", title: "Quên mật khẩu", description: "Yêu cầu đặt lại mật khẩu." },
  { path: "/reset-password", title: "Đặt lại mật khẩu", description: "Form đặt lại mật khẩu." },
];

export const candidateRoutes: AppRoute[] = [
  { path: "/candidate/dashboard", title: "Tổng quan ứng viên", description: "Tổng quan hồ sơ, CV, việc làm gợi ý và lịch sử ứng tuyển.", role: "candidate", nextPath: "/candidate/profile", nextLabel: "Hoàn thiện hồ sơ" },
  { path: "/candidate/jobs", title: "Tìm việc", description: "Danh sách việc làm dành cho ứng viên.", role: "candidate", nextPath: "/candidate/jobs/recommended", nextLabel: "Xem việc làm gợi ý" },
  { path: "/candidate/jobs/:jobId", title: "Chi tiết việc làm", description: "Chi tiết công việc và mức độ phù hợp với hồ sơ.", role: "candidate", nextPath: "/candidate/applications", nextLabel: "Ứng tuyển" },
  { path: "/candidate/jobs/recommended", title: "Việc làm gợi ý", description: "Danh sách công việc phù hợp với CV và hồ sơ cá nhân.", role: "candidate", nextPath: "/candidate/jobs/1", nextLabel: "Xem chi tiết" },
  { path: "/candidate/jobs/saved", title: "Việc làm đã lưu", description: "Các công việc ứng viên đã lưu.", role: "candidate" },
  { path: "/candidate/jobs/saved-searches", title: "Tìm kiếm đã lưu", description: "Các bộ lọc tìm kiếm đã lưu.", role: "candidate" },
  { path: "/candidate/profile", title: "Hồ sơ cá nhân", description: "Thông tin cá nhân, mục tiêu nghề nghiệp, học vấn và kỹ năng.", role: "candidate", nextPath: "/candidate/profile/edit", nextLabel: "Cập nhật hồ sơ" },
  { path: "/candidate/profile/edit", title: "Chỉnh sửa hồ sơ", description: "Cập nhật thông tin hồ sơ cá nhân.", role: "candidate", nextPath: "/candidate/profile/preferences", nextLabel: "Thiết lập mong muốn" },
  { path: "/candidate/profile/preferences", title: "Mong muốn nghề nghiệp", description: "Thiết lập vị trí, địa điểm và mức lương mong muốn.", role: "candidate", nextPath: "/candidate/cvs", nextLabel: "Quản lý CV" },
  { path: "/candidate/cvs", title: "Quản lý CV", description: "Danh sách CV và trạng thái phân tích.", role: "candidate", nextPath: "/candidate/cvs/upload", nextLabel: "Upload CV" },
  { path: "/candidate/cvs/upload", title: "Upload CV", description: "Tải lên CV và theo dõi trạng thái phân tích.", role: "candidate", nextPath: "/candidate/cvs/1/analysis", nextLabel: "Xem kết quả phân tích" },
  { path: "/candidate/cvs/:cvId", title: "Chi tiết CV", description: "Thông tin CV và metadata đã trích xuất.", role: "candidate" },
  { path: "/candidate/cvs/:cvId/analysis", title: "Kết quả phân tích CV", description: "Trạng thái phân tích CV và cảnh báo thiếu thông tin.", role: "candidate", nextPath: "/candidate/cvs/1/review", nextLabel: "Xem đánh giá CV" },
  { path: "/candidate/cvs/:cvId/edit-extracted-data", title: "Chỉnh sửa dữ liệu trích xuất", description: "Màn hình chỉnh sửa dữ liệu CV đã trích xuất.", role: "candidate", nextPath: "/candidate/cvs/1/analysis", nextLabel: "Xem phân tích CV" },
  { path: "/candidate/cvs/:cvId/review", title: "Đánh giá CV", description: "Nhận xét và gợi ý cải thiện CV.", role: "candidate", nextPath: "/candidate/jobs/recommended", nextLabel: "Xem việc làm gợi ý" },
  { path: "/candidate/applications", title: "Lịch sử ứng tuyển", description: "Danh sách đơn ứng tuyển và trạng thái xử lý.", role: "candidate", nextPath: "/candidate/applications/1", nextLabel: "Xem đơn ứng tuyển" },
  { path: "/candidate/applications/:applicationId", title: "Chi tiết đơn ứng tuyển", description: "Thông tin đơn ứng tuyển và timeline trạng thái.", role: "candidate", nextPath: "/candidate/applications/1/status", nextLabel: "Xem trạng thái" },
  { path: "/candidate/applications/:applicationId/status", title: "Trạng thái ứng tuyển", description: "Timeline trạng thái đơn ứng tuyển.", role: "candidate" },
  { path: "/candidate/interviews", title: "Lịch phỏng vấn", description: "Danh sách lịch phỏng vấn của ứng viên.", role: "candidate" },
  { path: "/candidate/interviews/:interviewId", title: "Chi tiết phỏng vấn", description: "Thông tin thời gian, hình thức và trạng thái phỏng vấn.", role: "candidate" },
  { path: "/candidate/invitations", title: "Lời mời ứng tuyển", description: "Danh sách lời mời ứng tuyển từ nhà tuyển dụng.", role: "candidate", nextPath: "/candidate/invitations/1", nextLabel: "Xem lời mời" },
  { path: "/candidate/invitations/:invitationId", title: "Chi tiết lời mời", description: "Nội dung lời mời và hành động chấp nhận hoặc từ chối.", role: "candidate" },
  { path: "/candidate/messages", title: "Tin nhắn", description: "Hộp thư trao đổi với nhà tuyển dụng.", role: "candidate" },
  { path: "/candidate/messages/:conversationId", title: "Chi tiết hội thoại", description: "Nội dung hội thoại.", role: "candidate" },
  { path: "/candidate/notifications", title: "Thông báo", description: "Thông báo về CV, việc làm, ứng tuyển và phỏng vấn.", role: "candidate" },
  { path: "/candidate/settings", title: "Cài đặt", description: "Cài đặt tài khoản ứng viên.", role: "candidate" },
  { path: "/candidate/settings/account", title: "Cài đặt tài khoản", description: "Thông tin tài khoản.", role: "candidate" },
  { path: "/candidate/settings/security", title: "Bảo mật", description: "Mật khẩu và phiên đăng nhập.", role: "candidate" },
  { path: "/candidate/settings/privacy", title: "Quyền riêng tư", description: "Kiểm soát hiển thị hồ sơ.", role: "candidate" },
  { path: "/candidate/settings/notifications", title: "Cài đặt thông báo", description: "Tùy chỉnh nhận thông báo.", role: "candidate" },
];

export const recruiterRoutes: AppRoute[] = [
  { path: "/recruiter/dashboard", title: "Tổng quan nhà tuyển dụng", description: "Tổng quan tin tuyển dụng, ứng viên và phỏng vấn.", role: "recruiter", nextPath: "/recruiter/company", nextLabel: "Cập nhật công ty" },
  { path: "/recruiter/company", title: "Hồ sơ công ty", description: "Thông tin doanh nghiệp và trạng thái xác thực.", role: "recruiter", nextPath: "/recruiter/company/edit", nextLabel: "Chỉnh sửa công ty" },
  { path: "/recruiter/company/edit", title: "Chỉnh sửa hồ sơ công ty", description: "Form cập nhật doanh nghiệp.", role: "recruiter", nextPath: "/recruiter/company/verification", nextLabel: "Gửi xác thực" },
  { path: "/recruiter/company/verification", title: "Xác thực doanh nghiệp", description: "Trạng thái chờ xác thực doanh nghiệp.", role: "recruiter", nextPath: "/recruiter/jobs/create", nextLabel: "Tạo tin tuyển dụng" },
  { path: "/recruiter/jobs", title: "Danh sách tin tuyển dụng", description: "Quản lý các tin tuyển dụng của công ty.", role: "recruiter", nextPath: "/recruiter/jobs/create", nextLabel: "Tạo tin mới" },
  { path: "/recruiter/jobs/create", title: "Tạo tin tuyển dụng", description: "Nhập thông tin cơ bản, mô tả và kỹ năng cho tin tuyển dụng.", role: "recruiter", nextPath: "/recruiter/jobs/1/preview", nextLabel: "Xem trước" },
  { path: "/recruiter/jobs/:jobId", title: "Chi tiết tin tuyển dụng", description: "Thông tin tin tuyển dụng và ứng viên liên quan.", role: "recruiter", nextPath: "/recruiter/recommended-candidates", nextLabel: "Xem ứng viên gợi ý" },
  { path: "/recruiter/jobs/:jobId/edit", title: "Chỉnh sửa tin tuyển dụng", description: "Cập nhật thông tin tin tuyển dụng.", role: "recruiter" },
  { path: "/recruiter/jobs/:jobId/preview", title: "Xem trước tin tuyển dụng", description: "Xem trước nội dung trước khi lưu nháp hoặc gửi duyệt.", role: "recruiter" },
  { path: "/recruiter/jobs/:jobId/statistics", title: "Thống kê tin tuyển dụng", description: "Số liệu hiển thị, ứng tuyển và tỷ lệ chuyển đổi.", role: "recruiter" },
  { path: "/recruiter/campaigns", title: "Chiến dịch tuyển dụng", description: "Danh sách chiến dịch tuyển dụng.", role: "recruiter" },
  { path: "/recruiter/campaigns/:campaignId", title: "Chi tiết chiến dịch", description: "Thông tin chiến dịch.", role: "recruiter" },
  { path: "/recruiter/candidates", title: "Tất cả ứng viên", description: "Danh sách ứng viên đã ứng tuyển.", role: "recruiter", nextPath: "/recruiter/pipeline", nextLabel: "Xem pipeline" },
  { path: "/recruiter/candidates/:candidateId", title: "Chi tiết ứng viên", description: "Hồ sơ, CV, điểm phù hợp và ghi chú nội bộ.", role: "recruiter", nextPath: "/recruiter/interviews/create", nextLabel: "Tạo lịch phỏng vấn" },
  { path: "/recruiter/candidates/:candidateId/evaluation", title: "Đánh giá ứng viên", description: "Đánh giá độ phù hợp của ứng viên.", role: "recruiter" },
  { path: "/recruiter/pipeline", title: "Pipeline tuyển dụng", description: "Kanban trạng thái ứng viên theo quy trình tuyển dụng.", role: "recruiter" },
  { path: "/recruiter/recommended-candidates", title: "Ứng viên được gợi ý", description: "Danh sách ứng viên phù hợp với tin tuyển dụng.", role: "recruiter" },
  { path: "/recruiter/saved-candidates", title: "Hồ sơ đã lưu", description: "Danh sách ứng viên đã lưu.", role: "recruiter" },
  { path: "/recruiter/candidate-search", title: "Tìm kiếm ứng viên", description: "Tìm ứng viên theo kỹ năng, kinh nghiệm và mục tiêu.", role: "recruiter" },
  { path: "/recruiter/interviews", title: "Phỏng vấn", description: "Lịch phỏng vấn và trạng thái xác nhận.", role: "recruiter" },
  { path: "/recruiter/interviews/create", title: "Tạo lịch phỏng vấn", description: "Chọn thời gian, hình thức, địa điểm và người phỏng vấn.", role: "recruiter" },
  { path: "/recruiter/interviews/:interviewId", title: "Chi tiết phỏng vấn", description: "Thông tin lịch phỏng vấn.", role: "recruiter" },
  { path: "/recruiter/messages", title: "Tin nhắn", description: "Hộp thư trao đổi với ứng viên.", role: "recruiter" },
  { path: "/recruiter/messages/:conversationId", title: "Chi tiết hội thoại", description: "Nội dung hội thoại.", role: "recruiter" },
  { path: "/recruiter/reports", title: "Báo cáo", description: "Báo cáo tuyển dụng và hiệu quả tin đăng.", role: "recruiter" },
  { path: "/recruiter/members", title: "Thành viên", description: "Quản lý thành viên công ty.", role: "recruiter" },
  { path: "/recruiter/members/invite", title: "Mời thành viên", description: "Mời thành viên tham gia tài khoản công ty.", role: "recruiter" },
  { path: "/recruiter/settings", title: "Cài đặt", description: "Cài đặt tài khoản nhà tuyển dụng.", role: "recruiter" },
  { path: "/recruiter/settings/account", title: "Tài khoản", description: "Thông tin tài khoản recruiter.", role: "recruiter" },
  { path: "/recruiter/settings/recruitment-process", title: "Quy trình tuyển dụng", description: "Cấu hình pipeline tuyển dụng.", role: "recruiter" },
  { path: "/recruiter/settings/email-templates", title: "Mẫu email", description: "Quản lý mẫu email tuyển dụng.", role: "recruiter" },
  { path: "/recruiter/settings/notifications", title: "Thông báo", description: "Cài đặt thông báo nhà tuyển dụng.", role: "recruiter" },
  { path: "/recruiter/settings/security", title: "Bảo mật", description: "Bảo mật tài khoản nhà tuyển dụng.", role: "recruiter" },
];

export const adminRoutes: AppRoute[] = [
  { path: "/admin/dashboard", title: "Tổng quan quản trị", description: "Tổng quan người dùng, doanh nghiệp, tin tuyển dụng và CV.", role: "admin", nextPath: "/admin/jobs/pending", nextLabel: "Duyệt tin chờ" },
  { path: "/admin/users", title: "Người dùng", description: "Quản lý tài khoản người dùng.", role: "admin" },
  { path: "/admin/users/:userId", title: "Chi tiết người dùng", description: "Thông tin người dùng.", role: "admin" },
  { path: "/admin/recruiters", title: "Nhà tuyển dụng", description: "Quản lý tài khoản nhà tuyển dụng.", role: "admin" },
  { path: "/admin/recruiters/:recruiterId", title: "Chi tiết nhà tuyển dụng", description: "Thông tin recruiter.", role: "admin" },
  { path: "/admin/companies", title: "Doanh nghiệp", description: "Quản lý doanh nghiệp và trạng thái xác thực.", role: "admin" },
  { path: "/admin/companies/:companyId", title: "Chi tiết doanh nghiệp", description: "Thông tin doanh nghiệp.", role: "admin" },
  { path: "/admin/companies/:companyId/verification", title: "Duyệt doanh nghiệp", description: "Duyệt hoặc từ chối xác thực doanh nghiệp.", role: "admin" },
  { path: "/admin/jobs", title: "Tin tuyển dụng", description: "Quản lý tin tuyển dụng trên hệ thống.", role: "admin" },
  { path: "/admin/jobs/pending", title: "Tin chờ duyệt", description: "Danh sách tin tuyển dụng cần kiểm tra.", role: "admin", nextPath: "/admin/jobs/1/review", nextLabel: "Duyệt tin" },
  { path: "/admin/jobs/:jobId", title: "Chi tiết tin tuyển dụng", description: "Chi tiết tin tuyển dụng trong admin.", role: "admin" },
  { path: "/admin/jobs/:jobId/review", title: "Duyệt tin tuyển dụng", description: "Duyệt, từ chối hoặc yêu cầu chỉnh sửa tin.", role: "admin" },
  { path: "/admin/applications", title: "Đơn ứng tuyển", description: "Theo dõi đơn ứng tuyển trên hệ thống.", role: "admin" },
  { path: "/admin/applications/:applicationId", title: "Chi tiết đơn ứng tuyển", description: "Thông tin đơn ứng tuyển.", role: "admin" },
  { path: "/admin/categories", title: "Danh mục", description: "Quản lý danh mục dùng chung.", role: "admin", nextPath: "/admin/categories/skills", nextLabel: "Quản lý kỹ năng" },
  { path: "/admin/categories/industries", title: "Ngành nghề", description: "Danh mục ngành nghề.", role: "admin" },
  { path: "/admin/categories/job-titles", title: "Chức danh", description: "Danh mục chức danh công việc.", role: "admin" },
  { path: "/admin/categories/skills", title: "Kỹ năng", description: "Danh mục kỹ năng.", role: "admin" },
  { path: "/admin/categories/locations", title: "Địa điểm", description: "Danh mục địa điểm.", role: "admin" },
  { path: "/admin/categories/job-types", title: "Loại việc làm", description: "Danh mục hình thức làm việc.", role: "admin" },
  { path: "/admin/categories/experience-levels", title: "Cấp bậc kinh nghiệm", description: "Danh mục kinh nghiệm.", role: "admin" },
  { path: "/admin/cv-analysis", title: "CV và thuật toán gợi ý", description: "Thống kê CV được phân tích và cấu hình gợi ý.", role: "admin" },
  { path: "/admin/cv-analysis/errors", title: "Lỗi phân tích CV", description: "Danh sách CV lỗi và lỗi trích xuất.", role: "admin" },
  { path: "/admin/recommendation-system", title: "Hệ thống gợi ý", description: "Tổng quan hệ thống gợi ý.", role: "admin" },
  { path: "/admin/recommendation-system/configuration", title: "Cấu hình gợi ý", description: "Cấu hình thuật toán gợi ý.", role: "admin" },
  { path: "/admin/content", title: "Nội dung", description: "Quản lý nội dung công khai.", role: "admin" },
  { path: "/admin/content/articles", title: "Bài viết", description: "Quản lý bài viết cẩm nang.", role: "admin" },
  { path: "/admin/content/banners", title: "Banner", description: "Quản lý banner hệ thống.", role: "admin" },
  { path: "/admin/content/pages", title: "Trang nội dung", description: "Quản lý trang tĩnh.", role: "admin" },
  { path: "/admin/reports", title: "Báo cáo vi phạm", description: "Danh sách báo cáo vi phạm.", role: "admin" },
  { path: "/admin/reports/:reportId", title: "Chi tiết báo cáo", description: "Chi tiết báo cáo vi phạm.", role: "admin" },
  { path: "/admin/analytics", title: "Thống kê", description: "Thống kê hệ thống.", role: "admin" },
  { path: "/admin/audit-logs", title: "Nhật ký hệ thống", description: "Theo dõi hành động quản trị.", role: "admin" },
  { path: "/admin/system-settings", title: "Cấu hình hệ thống", description: "Cấu hình chung của hệ thống.", role: "admin" },
];

export const allAppRoutes = [...publicRoutes, ...authRoutes, ...candidateRoutes, ...recruiterRoutes, ...adminRoutes];
