import type { AppRoute } from "../types/navigation";

export const publicRoutes: AppRoute[] = [
  { path: "/", title: "Trang chu", description: "Cong thong tin viec lam va goi y nghe nghiep cho sinh vien IT.", nextPath: "/jobs", nextLabel: "Tim viec lam" },
  { path: "/jobs", title: "Danh sach viec lam", description: "Tim kiem va loc cac cong viec phu hop.", nextPath: "/jobs/1", nextLabel: "Xem chi tiet viec lam" },
  { path: "/jobs/:jobId", title: "Chi tiet viec lam", description: "Thong tin vi tri, cong ty, yeu cau va muc do phu hop placeholder.", nextPath: "/login", nextLabel: "Dang nhap de ung tuyen" },
  { path: "/companies", title: "Danh sach cong ty", description: "Kham pha cac doanh nghiep dang tuyen dung.", nextPath: "/companies/1", nextLabel: "Xem cong ty" },
  { path: "/companies/:companyId", title: "Chi tiet cong ty", description: "Ho so cong ty va danh sach viec lam dang tuyen." },
  { path: "/career-resources", title: "Cam nang nghe nghiep", description: "Bai viet va tai nguyen dinh huong nghe nghiep.", nextPath: "/career-resources/cv-tips", nextLabel: "Doc bai viet" },
  { path: "/career-resources/:slug", title: "Chi tiet cam nang", description: "Noi dung bai viet nghe nghiep placeholder." },
  { path: "/about", title: "Gioi thieu", description: "Thong tin tong quan ve he thong goi y viec lam." },
  { path: "/contact", title: "Lien he", description: "Thong tin lien he va kenh ho tro placeholder." },
  { path: "/privacy-policy", title: "Chinh sach bao mat", description: "Chinh sach bao mat du lieu nguoi dung." },
  { path: "/terms", title: "Dieu khoan su dung", description: "Dieu khoan su dung nen tang." },
];

export const authRoutes: AppRoute[] = [
  { path: "/login", title: "Dang nhap", description: "Mock login de chuyen nhanh giua cac vai tro." },
  { path: "/register", title: "Dang ky", description: "Chon loai tai khoan ung vien hoac nha tuyen dung.", nextPath: "/register/candidate", nextLabel: "Dang ky ung vien" },
  { path: "/register/candidate", title: "Dang ky ung vien", description: "Form dang ky ung vien placeholder.", nextPath: "/login", nextLabel: "Den dang nhap" },
  { path: "/register/recruiter", title: "Dang ky nha tuyen dung", description: "Form dang ky nha tuyen dung placeholder.", nextPath: "/login", nextLabel: "Den dang nhap" },
  { path: "/forgot-password", title: "Quen mat khau", description: "Yeu cau dat lai mat khau placeholder." },
  { path: "/reset-password", title: "Dat lai mat khau", description: "Form dat lai mat khau placeholder." },
];

export const candidateRoutes: AppRoute[] = [
  { path: "/candidate/dashboard", title: "Candidate Dashboard", description: "Tong quan ho so, CV, viec lam goi y va lich su ung tuyen.", role: "candidate", nextPath: "/candidate/profile", nextLabel: "Hoan thien ho so" },
  { path: "/candidate/jobs", title: "Tim viec", description: "Danh sach viec lam danh cho ung vien.", role: "candidate", nextPath: "/candidate/jobs/recommended", nextLabel: "Xem viec lam goi y" },
  { path: "/candidate/jobs/:jobId", title: "Chi tiet viec lam", description: "Chi tiet cong viec va muc do phu hop voi ho so.", role: "candidate", nextPath: "/candidate/applications", nextLabel: "Ung tuyen" },
  { path: "/candidate/jobs/recommended", title: "Viec lam goi y", description: "Danh sach cong viec phu hop voi CV va ho so ca nhan.", role: "candidate", nextPath: "/candidate/jobs/1", nextLabel: "Xem chi tiet" },
  { path: "/candidate/jobs/saved", title: "Viec lam da luu", description: "Cac cong viec ung vien da luu.", role: "candidate" },
  { path: "/candidate/jobs/saved-searches", title: "Tim kiem da luu", description: "Cac bo loc tim kiem da luu.", role: "candidate" },
  { path: "/candidate/profile", title: "Ho so ca nhan", description: "Thong tin ca nhan, muc tieu nghe nghiep, hoc van va ky nang.", role: "candidate", nextPath: "/candidate/profile/edit", nextLabel: "Cap nhat ho so" },
  { path: "/candidate/profile/edit", title: "Chinh sua ho so", description: "Cap nhat thong tin ho so ca nhan placeholder.", role: "candidate", nextPath: "/candidate/profile/preferences", nextLabel: "Thiet lap mong muon" },
  { path: "/candidate/profile/preferences", title: "Mong muon nghe nghiep", description: "Thiet lap vi tri, dia diem va muc luong mong muon.", role: "candidate", nextPath: "/candidate/cvs", nextLabel: "Quan ly CV" },
  { path: "/candidate/cvs", title: "Quan ly CV", description: "Danh sach CV va trang thai phan tich.", role: "candidate", nextPath: "/candidate/cvs/upload", nextLabel: "Upload CV" },
  { path: "/candidate/cvs/upload", title: "Upload CV", description: "Tai len CV va theo doi trang thai phan tich placeholder.", role: "candidate", nextPath: "/candidate/cvs/1/analysis", nextLabel: "Xem ket qua phan tich" },
  { path: "/candidate/cvs/:cvId", title: "Chi tiet CV", description: "Thong tin CV va metadata da trich xuat.", role: "candidate" },
  { path: "/candidate/cvs/:cvId/analysis", title: "Ket qua phan tich CV", description: "Trang thai phan tich CV va canh bao thieu thong tin.", role: "candidate", nextPath: "/candidate/cvs/1/edit-extracted-data", nextLabel: "Kiem tra du lieu" },
  { path: "/candidate/cvs/:cvId/edit-extracted-data", title: "Chinh sua du lieu trich xuat", description: "Kiem tra va xac nhan du lieu lay tu CV.", role: "candidate", nextPath: "/candidate/cvs/1/review", nextLabel: "Xem danh gia CV" },
  { path: "/candidate/cvs/:cvId/review", title: "Danh gia CV", description: "Nhan xet va goi y cai thien CV placeholder.", role: "candidate", nextPath: "/candidate/jobs/recommended", nextLabel: "Xem viec lam goi y" },
  { path: "/candidate/applications", title: "Lich su ung tuyen", description: "Danh sach don ung tuyen va trang thai xu ly.", role: "candidate", nextPath: "/candidate/applications/1", nextLabel: "Xem don ung tuyen" },
  { path: "/candidate/applications/:applicationId", title: "Chi tiet don ung tuyen", description: "Thong tin don ung tuyen va timeline trang thai.", role: "candidate", nextPath: "/candidate/applications/1/status", nextLabel: "Xem trang thai" },
  { path: "/candidate/applications/:applicationId/status", title: "Trang thai ung tuyen", description: "Timeline trang thai don ung tuyen.", role: "candidate" },
  { path: "/candidate/interviews", title: "Lich phong van", description: "Danh sach lich phong van cua ung vien.", role: "candidate" },
  { path: "/candidate/interviews/:interviewId", title: "Chi tiet phong van", description: "Thong tin thoi gian, hinh thuc va trang thai phong van.", role: "candidate" },
  { path: "/candidate/invitations", title: "Loi moi ung tuyen", description: "Danh sach loi moi ung tuyen tu nha tuyen dung.", role: "candidate", nextPath: "/candidate/invitations/1", nextLabel: "Xem loi moi" },
  { path: "/candidate/invitations/:invitationId", title: "Chi tiet loi moi", description: "Noi dung loi moi va hanh dong chap nhan hoac tu choi.", role: "candidate" },
  { path: "/candidate/messages", title: "Tin nhan", description: "Hop thu trao doi voi nha tuyen dung.", role: "candidate" },
  { path: "/candidate/messages/:conversationId", title: "Chi tiet hoi thoai", description: "Noi dung hoi thoai placeholder.", role: "candidate" },
  { path: "/candidate/notifications", title: "Thong bao", description: "Thong bao ve CV, viec lam, ung tuyen va phong van.", role: "candidate" },
  { path: "/candidate/settings", title: "Cai dat", description: "Cai dat tai khoan ung vien.", role: "candidate" },
  { path: "/candidate/settings/account", title: "Cai dat tai khoan", description: "Thong tin tai khoan placeholder.", role: "candidate" },
  { path: "/candidate/settings/security", title: "Bao mat", description: "Mat khau va phien dang nhap placeholder.", role: "candidate" },
  { path: "/candidate/settings/privacy", title: "Quyen rieng tu", description: "Kiem soat hien thi ho so placeholder.", role: "candidate" },
  { path: "/candidate/settings/notifications", title: "Cai dat thong bao", description: "Tuy chinh nhan thong bao.", role: "candidate" },
];

export const recruiterRoutes: AppRoute[] = [
  { path: "/recruiter/dashboard", title: "Recruiter Dashboard", description: "Tong quan tin tuyen dung, ung vien va phong van.", role: "recruiter", nextPath: "/recruiter/company", nextLabel: "Cap nhat cong ty" },
  { path: "/recruiter/company", title: "Ho so cong ty", description: "Thong tin doanh nghiep va trang thai xac thuc.", role: "recruiter", nextPath: "/recruiter/company/edit", nextLabel: "Chinh sua cong ty" },
  { path: "/recruiter/company/edit", title: "Chinh sua ho so cong ty", description: "Form cap nhat doanh nghiep placeholder.", role: "recruiter", nextPath: "/recruiter/company/verification", nextLabel: "Gui xac thuc" },
  { path: "/recruiter/company/verification", title: "Xac thuc doanh nghiep", description: "Trang thai cho xac thuc doanh nghiep.", role: "recruiter", nextPath: "/recruiter/jobs/create", nextLabel: "Tao tin tuyen dung" },
  { path: "/recruiter/jobs", title: "Danh sach tin tuyen dung", description: "Quan ly cac tin tuyen dung cua cong ty.", role: "recruiter", nextPath: "/recruiter/jobs/create", nextLabel: "Tao tin moi" },
  { path: "/recruiter/jobs/create", title: "Tao tin tuyen dung", description: "Nhap thong tin co ban, mo ta, ky nang va cau hoi sang loc placeholder.", role: "recruiter", nextPath: "/recruiter/jobs/1/preview", nextLabel: "Xem truoc" },
  { path: "/recruiter/jobs/:jobId", title: "Chi tiet tin tuyen dung", description: "Thong tin tin tuyen dung va ung vien lien quan.", role: "recruiter", nextPath: "/recruiter/recommended-candidates", nextLabel: "Xem ung vien goi y" },
  { path: "/recruiter/jobs/:jobId/edit", title: "Chinh sua tin tuyen dung", description: "Cap nhat thong tin tin tuyen dung placeholder.", role: "recruiter" },
  { path: "/recruiter/jobs/:jobId/preview", title: "Xem truoc tin tuyen dung", description: "Xem truoc noi dung truoc khi luu nhap hoac gui duyet.", role: "recruiter" },
  { path: "/recruiter/jobs/:jobId/statistics", title: "Thong ke tin tuyen dung", description: "So lieu hien thi, ung tuyen va ty le chuyen doi placeholder.", role: "recruiter" },
  { path: "/recruiter/campaigns", title: "Chien dich tuyen dung", description: "Danh sach chien dich tuyen dung.", role: "recruiter" },
  { path: "/recruiter/campaigns/:campaignId", title: "Chi tiet chien dich", description: "Thong tin chien dich placeholder.", role: "recruiter" },
  { path: "/recruiter/candidates", title: "Tat ca ung vien", description: "Danh sach ung vien da ung tuyen.", role: "recruiter", nextPath: "/recruiter/pipeline", nextLabel: "Xem pipeline" },
  { path: "/recruiter/candidates/:candidateId", title: "Chi tiet ung vien", description: "Ho so, CV, diem phu hop va ghi chu noi bo.", role: "recruiter", nextPath: "/recruiter/interviews/create", nextLabel: "Tao lich phong van" },
  { path: "/recruiter/candidates/:candidateId/evaluation", title: "Danh gia ung vien", description: "Danh gia do phu hop cua ung vien.", role: "recruiter" },
  { path: "/recruiter/pipeline", title: "Pipeline tuyen dung", description: "Kanban trang thai ung vien theo quy trinh tuyen dung.", role: "recruiter" },
  { path: "/recruiter/recommended-candidates", title: "Ung vien duoc goi y", description: "Danh sach ung vien phu hop voi tin tuyen dung.", role: "recruiter" },
  { path: "/recruiter/saved-candidates", title: "Ho so da luu", description: "Danh sach ung vien da luu.", role: "recruiter" },
  { path: "/recruiter/candidate-search", title: "Tim kiem ung vien", description: "Tim ung vien theo ky nang, kinh nghiem va muc tieu.", role: "recruiter" },
  { path: "/recruiter/interviews", title: "Phong van", description: "Lich phong van va trang thai xac nhan.", role: "recruiter" },
  { path: "/recruiter/interviews/create", title: "Tao lich phong van", description: "Chon thoi gian, hinh thuc, dia diem va nguoi phong van.", role: "recruiter" },
  { path: "/recruiter/interviews/:interviewId", title: "Chi tiet phong van", description: "Thong tin lich phong van placeholder.", role: "recruiter" },
  { path: "/recruiter/messages", title: "Tin nhan", description: "Hop thu trao doi voi ung vien.", role: "recruiter" },
  { path: "/recruiter/messages/:conversationId", title: "Chi tiet hoi thoai", description: "Noi dung hoi thoai placeholder.", role: "recruiter" },
  { path: "/recruiter/reports", title: "Bao cao", description: "Bao cao tuyen dung va hieu qua tin dang.", role: "recruiter" },
  { path: "/recruiter/members", title: "Thanh vien", description: "Quan ly thanh vien cong ty.", role: "recruiter" },
  { path: "/recruiter/members/invite", title: "Moi thanh vien", description: "Moi thanh vien tham gia tai khoan cong ty.", role: "recruiter" },
  { path: "/recruiter/settings", title: "Cai dat", description: "Cai dat tai khoan nha tuyen dung.", role: "recruiter" },
  { path: "/recruiter/settings/account", title: "Tai khoan", description: "Thong tin tai khoan recruiter.", role: "recruiter" },
  { path: "/recruiter/settings/recruitment-process", title: "Quy trinh tuyen dung", description: "Cau hinh pipeline tuyen dung placeholder.", role: "recruiter" },
  { path: "/recruiter/settings/email-templates", title: "Mau email", description: "Quan ly mau email tuyen dung.", role: "recruiter" },
  { path: "/recruiter/settings/notifications", title: "Thong bao", description: "Cai dat thong bao nha tuyen dung.", role: "recruiter" },
  { path: "/recruiter/settings/security", title: "Bao mat", description: "Bao mat tai khoan nha tuyen dung.", role: "recruiter" },
];

export const adminRoutes: AppRoute[] = [
  { path: "/admin/dashboard", title: "Admin Dashboard", description: "Tong quan nguoi dung, doanh nghiep, tin tuyen dung va CV.", role: "admin", nextPath: "/admin/jobs/pending", nextLabel: "Duyet tin cho" },
  { path: "/admin/users", title: "Nguoi dung", description: "Quan ly tai khoan nguoi dung.", role: "admin" },
  { path: "/admin/users/:userId", title: "Chi tiet nguoi dung", description: "Thong tin nguoi dung placeholder.", role: "admin" },
  { path: "/admin/recruiters", title: "Nha tuyen dung", description: "Quan ly tai khoan nha tuyen dung.", role: "admin" },
  { path: "/admin/recruiters/:recruiterId", title: "Chi tiet nha tuyen dung", description: "Thong tin recruiter placeholder.", role: "admin" },
  { path: "/admin/companies", title: "Doanh nghiep", description: "Quan ly doanh nghiep va trang thai xac thuc.", role: "admin" },
  { path: "/admin/companies/:companyId", title: "Chi tiet doanh nghiep", description: "Thong tin doanh nghiep placeholder.", role: "admin" },
  { path: "/admin/companies/:companyId/verification", title: "Duyet doanh nghiep", description: "Duyet hoac tu choi xac thuc doanh nghiep.", role: "admin" },
  { path: "/admin/jobs", title: "Tin tuyen dung", description: "Quan ly tin tuyen dung tren he thong.", role: "admin" },
  { path: "/admin/jobs/pending", title: "Tin cho duyet", description: "Danh sach tin tuyen dung can kiem tra.", role: "admin", nextPath: "/admin/jobs/1/review", nextLabel: "Duyet tin" },
  { path: "/admin/jobs/:jobId", title: "Chi tiet tin tuyen dung", description: "Chi tiet tin tuyen dung trong admin.", role: "admin" },
  { path: "/admin/jobs/:jobId/review", title: "Duyet tin tuyen dung", description: "Duyet, tu choi hoac yeu cau chinh sua tin.", role: "admin" },
  { path: "/admin/applications", title: "Don ung tuyen", description: "Theo doi don ung tuyen tren he thong.", role: "admin" },
  { path: "/admin/applications/:applicationId", title: "Chi tiet don ung tuyen", description: "Thong tin don ung tuyen placeholder.", role: "admin" },
  { path: "/admin/categories", title: "Danh muc", description: "Quan ly danh muc dung chung.", role: "admin", nextPath: "/admin/categories/skills", nextLabel: "Quan ly ky nang" },
  { path: "/admin/categories/industries", title: "Nganh nghe", description: "Danh muc nganh nghe.", role: "admin" },
  { path: "/admin/categories/job-titles", title: "Chuc danh", description: "Danh muc chuc danh cong viec.", role: "admin" },
  { path: "/admin/categories/skills", title: "Ky nang", description: "Danh muc ky nang.", role: "admin" },
  { path: "/admin/categories/locations", title: "Dia diem", description: "Danh muc dia diem.", role: "admin" },
  { path: "/admin/categories/job-types", title: "Loai viec lam", description: "Danh muc hinh thuc lam viec.", role: "admin" },
  { path: "/admin/categories/experience-levels", title: "Cap bac kinh nghiem", description: "Danh muc kinh nghiem.", role: "admin" },
  { path: "/admin/cv-analysis", title: "CV va thuat toan goi y", description: "Thong ke CV duoc phan tich va cau hinh goi y placeholder.", role: "admin" },
  { path: "/admin/cv-analysis/errors", title: "Loi phan tich CV", description: "Danh sach CV loi va loi trich xuat.", role: "admin" },
  { path: "/admin/recommendation-system", title: "He thong goi y", description: "Tong quan he thong goi y placeholder.", role: "admin" },
  { path: "/admin/recommendation-system/configuration", title: "Cau hinh goi y", description: "Cau hinh thuat toan goi y placeholder.", role: "admin" },
  { path: "/admin/content", title: "Noi dung", description: "Quan ly noi dung cong khai.", role: "admin" },
  { path: "/admin/content/articles", title: "Bai viet", description: "Quan ly bai viet cam nang.", role: "admin" },
  { path: "/admin/content/banners", title: "Banner", description: "Quan ly banner he thong.", role: "admin" },
  { path: "/admin/content/pages", title: "Trang noi dung", description: "Quan ly trang tinh.", role: "admin" },
  { path: "/admin/reports", title: "Bao cao vi pham", description: "Danh sach bao cao vi pham.", role: "admin" },
  { path: "/admin/reports/:reportId", title: "Chi tiet bao cao", description: "Chi tiet bao cao vi pham placeholder.", role: "admin" },
  { path: "/admin/analytics", title: "Thong ke", description: "Thong ke he thong.", role: "admin" },
  { path: "/admin/audit-logs", title: "Nhat ky he thong", description: "Theo doi hanh dong quan tri.", role: "admin" },
  { path: "/admin/system-settings", title: "Cau hinh he thong", description: "Cau hinh chung cua he thong.", role: "admin" },
];

export const allAppRoutes = [...publicRoutes, ...authRoutes, ...candidateRoutes, ...recruiterRoutes, ...adminRoutes];
